# Generated by Django 6.1 on 2026-09-17 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pets',
            new_name='Pet',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='Typeofpet',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='descriptionofpet',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='petowner',
            new_name='owner',
        ),
    ]
